### PR TITLE
Add on off toggle and more info

### PR DESCRIPTION
**Pull request by swingerman**
Added on-off toggle icon and functionality as well as added touch hold and context menu click handling to show more info.

- added toggle button to make it possible to toggle the thermostat
- added context menu click handling that opens more info (aimed for desktop use)
- added tap-hold (hold action) handling that opens more info (aimed for mobile use)

### CODE REVIEW

**Comment by swingerman** [comment]
Hello @ciotlosm, would you mind to review this PR?

**Comment by ciotlosm** [comment]
Will review on the next days

**Comment by MikeCodesDotNET** [comment]
Any update on merging this @ciotlosm?

**Comment by amaciuc** [comment]
Any updates?

**Comment by swingerman** [comment]
Hi @ciotlosm would you please merge this? 🙏

**Comment by mikesn31** [comment]
How do I disable / hid the new power button toggle? its not working correctly with Nest thermostat

**Pull request merged**
